profiles: dev
server:
  port: 9000
spring:
  application:
    name: user-center
  cloud:
    config:
      uri:
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
